// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: delete_account.sql

package sqlc

import (
	"context"
)

const deleteAccount = `-- name: DeleteAccount :exec
DELETE from accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}
