// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: get_accounts.sql

package sqlc

import (
	"context"
)

const getAccounts = `-- name: GetAccounts :many
SELECT id, owner, balance, currency, created_at from accounts
ORDER BY name
`

func (q *Queries) GetAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
