// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: insert_init_account.sql

package sqlc

import (
	"context"
)

const insertIntoAccount = `-- name: InsertIntoAccount :one
INSERT INTO accounts (
	owner,
	balance,
	currency
) VALUES (
	$1, $2, $3
) RETURNING id, owner, balance, currency, created_at
`

type InsertIntoAccountParams struct {
	Owner    string
	Balance  int64
	Currency string
}

func (q *Queries) InsertIntoAccount(ctx context.Context, arg InsertIntoAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, insertIntoAccount, arg.Owner, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
